package com.glodon.demo.mybatis.mappers;

import com.glodon.demo.mybatis.models.SimsClass;
import com.glodon.demo.mybatis.models.SimsStudent;

import java.util.List;

public interface SimsClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_class
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_class
     *
     * @mbggenerated
     */
    int insert(SimsClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_class
     *
     * @mbggenerated
     */
    SimsClass selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_class
     *
     * @mbggenerated
     */
    List<SimsClass> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_class
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SimsClass record);

    List<SimsStudent> getStudentsWithSameClass(String classId);
}