package com.glodon.demo.mybatis.models;

import java.util.Date;

public class SimsMajor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_major.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_major.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_major.SHORT_NAME
     *
     * @mbggenerated
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_major.ESTAB_DATE
     *
     * @mbggenerated
     */
    private Date estabDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_major.INTRO
     *
     * @mbggenerated
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_major.TUITION_FEE
     *
     * @mbggenerated
     */
    private String tuitionFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_major.CREATED_BY
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_major.CREATED_TIME
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_major.UPDATED_BY
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_major.UPDATED_TIME
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_major.ID
     *
     * @return the value of sims_major.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_major.ID
     *
     * @param id the value for sims_major.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_major.NAME
     *
     * @return the value of sims_major.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_major.NAME
     *
     * @param name the value for sims_major.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_major.SHORT_NAME
     *
     * @return the value of sims_major.SHORT_NAME
     *
     * @mbggenerated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_major.SHORT_NAME
     *
     * @param shortName the value for sims_major.SHORT_NAME
     *
     * @mbggenerated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_major.ESTAB_DATE
     *
     * @return the value of sims_major.ESTAB_DATE
     *
     * @mbggenerated
     */
    public Date getEstabDate() {
        return estabDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_major.ESTAB_DATE
     *
     * @param estabDate the value for sims_major.ESTAB_DATE
     *
     * @mbggenerated
     */
    public void setEstabDate(Date estabDate) {
        this.estabDate = estabDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_major.INTRO
     *
     * @return the value of sims_major.INTRO
     *
     * @mbggenerated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_major.INTRO
     *
     * @param intro the value for sims_major.INTRO
     *
     * @mbggenerated
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_major.TUITION_FEE
     *
     * @return the value of sims_major.TUITION_FEE
     *
     * @mbggenerated
     */
    public String getTuitionFee() {
        return tuitionFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_major.TUITION_FEE
     *
     * @param tuitionFee the value for sims_major.TUITION_FEE
     *
     * @mbggenerated
     */
    public void setTuitionFee(String tuitionFee) {
        this.tuitionFee = tuitionFee == null ? null : tuitionFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_major.CREATED_BY
     *
     * @return the value of sims_major.CREATED_BY
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_major.CREATED_BY
     *
     * @param createdBy the value for sims_major.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_major.CREATED_TIME
     *
     * @return the value of sims_major.CREATED_TIME
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_major.CREATED_TIME
     *
     * @param createdTime the value for sims_major.CREATED_TIME
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_major.UPDATED_BY
     *
     * @return the value of sims_major.UPDATED_BY
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_major.UPDATED_BY
     *
     * @param updatedBy the value for sims_major.UPDATED_BY
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_major.UPDATED_TIME
     *
     * @return the value of sims_major.UPDATED_TIME
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_major.UPDATED_TIME
     *
     * @param updatedTime the value for sims_major.UPDATED_TIME
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}