package com.glodon.demo.mybatis.models;

import java.util.Date;

public class SimsCollege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_college.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_college.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_college.SHORT_NAME
     *
     * @mbggenerated
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_college.INTRO
     *
     * @mbggenerated
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_college.PROFESSION_NUMBER
     *
     * @mbggenerated
     */
    private Integer professionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_college.STUDENT_NUMBER
     *
     * @mbggenerated
     */
    private Integer studentNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_college.PRESIDENT
     *
     * @mbggenerated
     */
    private String president;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_college.CREATED_BY
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_college.CREATED_TIME
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_college.UPDATED_BY
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_college.UPDATED_TIME
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_college.ID
     *
     * @return the value of sims_college.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_college.ID
     *
     * @param id the value for sims_college.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_college.NAME
     *
     * @return the value of sims_college.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_college.NAME
     *
     * @param name the value for sims_college.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_college.SHORT_NAME
     *
     * @return the value of sims_college.SHORT_NAME
     *
     * @mbggenerated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_college.SHORT_NAME
     *
     * @param shortName the value for sims_college.SHORT_NAME
     *
     * @mbggenerated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_college.INTRO
     *
     * @return the value of sims_college.INTRO
     *
     * @mbggenerated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_college.INTRO
     *
     * @param intro the value for sims_college.INTRO
     *
     * @mbggenerated
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_college.PROFESSION_NUMBER
     *
     * @return the value of sims_college.PROFESSION_NUMBER
     *
     * @mbggenerated
     */
    public Integer getProfessionNumber() {
        return professionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_college.PROFESSION_NUMBER
     *
     * @param professionNumber the value for sims_college.PROFESSION_NUMBER
     *
     * @mbggenerated
     */
    public void setProfessionNumber(Integer professionNumber) {
        this.professionNumber = professionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_college.STUDENT_NUMBER
     *
     * @return the value of sims_college.STUDENT_NUMBER
     *
     * @mbggenerated
     */
    public Integer getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_college.STUDENT_NUMBER
     *
     * @param studentNumber the value for sims_college.STUDENT_NUMBER
     *
     * @mbggenerated
     */
    public void setStudentNumber(Integer studentNumber) {
        this.studentNumber = studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_college.PRESIDENT
     *
     * @return the value of sims_college.PRESIDENT
     *
     * @mbggenerated
     */
    public String getPresident() {
        return president;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_college.PRESIDENT
     *
     * @param president the value for sims_college.PRESIDENT
     *
     * @mbggenerated
     */
    public void setPresident(String president) {
        this.president = president == null ? null : president.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_college.CREATED_BY
     *
     * @return the value of sims_college.CREATED_BY
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_college.CREATED_BY
     *
     * @param createdBy the value for sims_college.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_college.CREATED_TIME
     *
     * @return the value of sims_college.CREATED_TIME
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_college.CREATED_TIME
     *
     * @param createdTime the value for sims_college.CREATED_TIME
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_college.UPDATED_BY
     *
     * @return the value of sims_college.UPDATED_BY
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_college.UPDATED_BY
     *
     * @param updatedBy the value for sims_college.UPDATED_BY
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_college.UPDATED_TIME
     *
     * @return the value of sims_college.UPDATED_TIME
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_college.UPDATED_TIME
     *
     * @param updatedTime the value for sims_college.UPDATED_TIME
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}