package com.glodon.demo.mybatis.mappers;

import com.glodon.demo.mybatis.models.SimsLesson;
import java.util.List;

public interface SimsLessonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_lesson
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_lesson
     *
     * @mbggenerated
     */
    int insert(SimsLesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_lesson
     *
     * @mbggenerated
     */
    SimsLesson selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_lesson
     *
     * @mbggenerated
     */
    List<SimsLesson> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_lesson
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SimsLesson record);
}