package com.glodon.demo.mybatis.mappers;

import com.glodon.demo.mybatis.models.SimsCollege;
import java.util.List;

public interface SimsCollegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_college
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_college
     *
     * @mbggenerated
     */
    int insert(SimsCollege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_college
     *
     * @mbggenerated
     */
    SimsCollege selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_college
     *
     * @mbggenerated
     */
    List<SimsCollege> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_college
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SimsCollege record);
}