package com.glodon.demo.mybatis.mappers;

import com.glodon.demo.mybatis.models.SimsInstruct;
import java.util.List;

public interface SimsInstructMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_instruct
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_instruct
     *
     * @mbggenerated
     */
    int insert(SimsInstruct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_instruct
     *
     * @mbggenerated
     */
    SimsInstruct selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_instruct
     *
     * @mbggenerated
     */
    List<SimsInstruct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_instruct
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SimsInstruct record);
}