package com.glodon.demo.mybatis.mappers;

import com.glodon.demo.mybatis.models.SimsMajor;
import java.util.List;

public interface SimsMajorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_major
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_major
     *
     * @mbggenerated
     */
    int insert(SimsMajor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_major
     *
     * @mbggenerated
     */
    SimsMajor selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_major
     *
     * @mbggenerated
     */
    List<SimsMajor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_major
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SimsMajor record);
}