package com.glodon.demo.mybatis.mappers;

import com.glodon.demo.mybatis.dtos.SimsStudentDto;
import com.glodon.demo.mybatis.models.SimsStudent;
import com.glodon.demo.mybatis.models.StudentWithClass;

import java.util.List;

public interface SimsStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_student
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_student
     *
     * @mbggenerated
     */
    int insert(SimsStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_student
     *
     * @mbggenerated
     */
    SimsStudent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_student
     *
     * @mbggenerated
     */
    List<SimsStudent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SimsStudent record);

    SimsStudent getStudentByName(String name);

    List<StudentWithClass> selectByNameWithClass(String name);
}