package com.glodon.demo.mybatis.mappers;

import com.glodon.demo.mybatis.models.SimsTeacher;
import java.util.List;

public interface SimsTeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_teacher
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_teacher
     *
     * @mbggenerated
     */
    int insert(SimsTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_teacher
     *
     * @mbggenerated
     */
    SimsTeacher selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_teacher
     *
     * @mbggenerated
     */
    List<SimsTeacher> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sims_teacher
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SimsTeacher record);
}