package com.glodon.demo.mybatis.models;

import java.math.BigDecimal;
import java.util.Date;

public class SimsStudent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.ID
     *
     * @mbggenerated
     */
    private String id;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.COLLEGE_ID
     *
     * @mbggenerated
     */
    private String collegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.CLASS_ID
     *
     * @mbggenerated
     */
    private String classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.ID_CARD_NO
     *
     * @mbggenerated
     */
    private String idCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.ENG_NAME
     *
     * @mbggenerated
     */
    private String engName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.MOBILE_PHONE
     *
     * @mbggenerated
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.GENDER
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.BIRTH
     *
     * @mbggenerated
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.AVATAR
     *
     * @mbggenerated
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.HEIGHT
     *
     * @mbggenerated
     */
    private BigDecimal height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.WEIGHT
     *
     * @mbggenerated
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.NATION
     *
     * @mbggenerated
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.POLITICAL
     *
     * @mbggenerated
     */
    private String political;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.MARITAL
     *
     * @mbggenerated
     */
    private String marital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.DOMICILE_PLACE_PROVINCE
     *
     * @mbggenerated
     */
    private String domicilePlaceProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.DOMICILE_PLACE_CITY
     *
     * @mbggenerated
     */
    private String domicilePlaceCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.DOMICILE_PLACE_ADDRESS
     *
     * @mbggenerated
     */
    private String domicilePlaceAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.HOBBY
     *
     * @mbggenerated
     */
    private String hobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.INTRO
     *
     * @mbggenerated
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.PRESENT_ADDRESS
     *
     * @mbggenerated
     */
    private String presentAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.ENTRY_DATE
     *
     * @mbggenerated
     */
    private Date entryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.CREATED_BY
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.CREATED_TIME
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.UPDATED_BY
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_student.UPDATED_TIME
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.ID
     *
     * @return the value of sims_student.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.ID
     *
     * @param id the value for sims_student.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.COLLEGE_ID
     *
     * @return the value of sims_student.COLLEGE_ID
     *
     * @mbggenerated
     */
    public String getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.COLLEGE_ID
     *
     * @param collegeId the value for sims_student.COLLEGE_ID
     *
     * @mbggenerated
     */
    public void setCollegeId(String collegeId) {
        this.collegeId = collegeId == null ? null : collegeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.CLASS_ID
     *
     * @return the value of sims_student.CLASS_ID
     *
     * @mbggenerated
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.CLASS_ID
     *
     * @param classId the value for sims_student.CLASS_ID
     *
     * @mbggenerated
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.NAME
     *
     * @return the value of sims_student.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.NAME
     *
     * @param name the value for sims_student.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.ID_CARD_NO
     *
     * @return the value of sims_student.ID_CARD_NO
     *
     * @mbggenerated
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.ID_CARD_NO
     *
     * @param idCardNo the value for sims_student.ID_CARD_NO
     *
     * @mbggenerated
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo == null ? null : idCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.ENG_NAME
     *
     * @return the value of sims_student.ENG_NAME
     *
     * @mbggenerated
     */
    public String getEngName() {
        return engName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.ENG_NAME
     *
     * @param engName the value for sims_student.ENG_NAME
     *
     * @mbggenerated
     */
    public void setEngName(String engName) {
        this.engName = engName == null ? null : engName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.MOBILE_PHONE
     *
     * @return the value of sims_student.MOBILE_PHONE
     *
     * @mbggenerated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.MOBILE_PHONE
     *
     * @param mobilePhone the value for sims_student.MOBILE_PHONE
     *
     * @mbggenerated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.GENDER
     *
     * @return the value of sims_student.GENDER
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.GENDER
     *
     * @param gender the value for sims_student.GENDER
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.BIRTH
     *
     * @return the value of sims_student.BIRTH
     *
     * @mbggenerated
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.BIRTH
     *
     * @param birth the value for sims_student.BIRTH
     *
     * @mbggenerated
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.AVATAR
     *
     * @return the value of sims_student.AVATAR
     *
     * @mbggenerated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.AVATAR
     *
     * @param avatar the value for sims_student.AVATAR
     *
     * @mbggenerated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.HEIGHT
     *
     * @return the value of sims_student.HEIGHT
     *
     * @mbggenerated
     */
    public BigDecimal getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.HEIGHT
     *
     * @param height the value for sims_student.HEIGHT
     *
     * @mbggenerated
     */
    public void setHeight(BigDecimal height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.WEIGHT
     *
     * @return the value of sims_student.WEIGHT
     *
     * @mbggenerated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.WEIGHT
     *
     * @param weight the value for sims_student.WEIGHT
     *
     * @mbggenerated
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.NATION
     *
     * @return the value of sims_student.NATION
     *
     * @mbggenerated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.NATION
     *
     * @param nation the value for sims_student.NATION
     *
     * @mbggenerated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.POLITICAL
     *
     * @return the value of sims_student.POLITICAL
     *
     * @mbggenerated
     */
    public String getPolitical() {
        return political;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.POLITICAL
     *
     * @param political the value for sims_student.POLITICAL
     *
     * @mbggenerated
     */
    public void setPolitical(String political) {
        this.political = political == null ? null : political.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.MARITAL
     *
     * @return the value of sims_student.MARITAL
     *
     * @mbggenerated
     */
    public String getMarital() {
        return marital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.MARITAL
     *
     * @param marital the value for sims_student.MARITAL
     *
     * @mbggenerated
     */
    public void setMarital(String marital) {
        this.marital = marital == null ? null : marital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.DOMICILE_PLACE_PROVINCE
     *
     * @return the value of sims_student.DOMICILE_PLACE_PROVINCE
     *
     * @mbggenerated
     */
    public String getDomicilePlaceProvince() {
        return domicilePlaceProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.DOMICILE_PLACE_PROVINCE
     *
     * @param domicilePlaceProvince the value for sims_student.DOMICILE_PLACE_PROVINCE
     *
     * @mbggenerated
     */
    public void setDomicilePlaceProvince(String domicilePlaceProvince) {
        this.domicilePlaceProvince = domicilePlaceProvince == null ? null : domicilePlaceProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.DOMICILE_PLACE_CITY
     *
     * @return the value of sims_student.DOMICILE_PLACE_CITY
     *
     * @mbggenerated
     */
    public String getDomicilePlaceCity() {
        return domicilePlaceCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.DOMICILE_PLACE_CITY
     *
     * @param domicilePlaceCity the value for sims_student.DOMICILE_PLACE_CITY
     *
     * @mbggenerated
     */
    public void setDomicilePlaceCity(String domicilePlaceCity) {
        this.domicilePlaceCity = domicilePlaceCity == null ? null : domicilePlaceCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.DOMICILE_PLACE_ADDRESS
     *
     * @return the value of sims_student.DOMICILE_PLACE_ADDRESS
     *
     * @mbggenerated
     */
    public String getDomicilePlaceAddress() {
        return domicilePlaceAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.DOMICILE_PLACE_ADDRESS
     *
     * @param domicilePlaceAddress the value for sims_student.DOMICILE_PLACE_ADDRESS
     *
     * @mbggenerated
     */
    public void setDomicilePlaceAddress(String domicilePlaceAddress) {
        this.domicilePlaceAddress = domicilePlaceAddress == null ? null : domicilePlaceAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.HOBBY
     *
     * @return the value of sims_student.HOBBY
     *
     * @mbggenerated
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.HOBBY
     *
     * @param hobby the value for sims_student.HOBBY
     *
     * @mbggenerated
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.INTRO
     *
     * @return the value of sims_student.INTRO
     *
     * @mbggenerated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.INTRO
     *
     * @param intro the value for sims_student.INTRO
     *
     * @mbggenerated
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.PRESENT_ADDRESS
     *
     * @return the value of sims_student.PRESENT_ADDRESS
     *
     * @mbggenerated
     */
    public String getPresentAddress() {
        return presentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.PRESENT_ADDRESS
     *
     * @param presentAddress the value for sims_student.PRESENT_ADDRESS
     *
     * @mbggenerated
     */
    public void setPresentAddress(String presentAddress) {
        this.presentAddress = presentAddress == null ? null : presentAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.EMAIL
     *
     * @return the value of sims_student.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.EMAIL
     *
     * @param email the value for sims_student.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.ENTRY_DATE
     *
     * @return the value of sims_student.ENTRY_DATE
     *
     * @mbggenerated
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.ENTRY_DATE
     *
     * @param entryDate the value for sims_student.ENTRY_DATE
     *
     * @mbggenerated
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.STATUS
     *
     * @return the value of sims_student.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.STATUS
     *
     * @param status the value for sims_student.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.CREATED_BY
     *
     * @return the value of sims_student.CREATED_BY
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.CREATED_BY
     *
     * @param createdBy the value for sims_student.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.CREATED_TIME
     *
     * @return the value of sims_student.CREATED_TIME
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.CREATED_TIME
     *
     * @param createdTime the value for sims_student.CREATED_TIME
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.UPDATED_BY
     *
     * @return the value of sims_student.UPDATED_BY
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.UPDATED_BY
     *
     * @param updatedBy the value for sims_student.UPDATED_BY
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_student.UPDATED_TIME
     *
     * @return the value of sims_student.UPDATED_TIME
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_student.UPDATED_TIME
     *
     * @param updatedTime the value for sims_student.UPDATED_TIME
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}