spring:
  application:
    name: mybatis-spring-demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spikesystem?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true
    username: root
    password: 123456
mybatis:
  mapper-locations:
    classpath: com/glodon/demo/mybatis/mappers/*.xml
