package com.glodon.demo.mybatis.dtos;

import java.util.Date;

public class SimsClassDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.COLLEGE_ID
     *
     * @mbggenerated
     */
    private String collegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.MAJOR_ID
     *
     * @mbggenerated
     */
    private String majorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.STUDENT_NUMBER
     *
     * @mbggenerated
     */
    private Integer studentNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.ADVISER
     *
     * @mbggenerated
     */
    private String adviser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.ESTAB_DATE
     *
     * @mbggenerated
     */
    private Date estabDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.YEAR_NUMBER
     *
     * @mbggenerated
     */
    private Integer yearNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.CRATED_BY
     *
     * @mbggenerated
     */
    private String cratedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.CRATED_TIME
     *
     * @mbggenerated
     */
    private Date cratedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.UPDATED_BY
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sims_class.UPDATED_TIME
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.ID
     *
     * @return the value of sims_class.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.ID
     *
     * @param id the value for sims_class.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.COLLEGE_ID
     *
     * @return the value of sims_class.COLLEGE_ID
     *
     * @mbggenerated
     */
    public String getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.COLLEGE_ID
     *
     * @param collegeId the value for sims_class.COLLEGE_ID
     *
     * @mbggenerated
     */
    public void setCollegeId(String collegeId) {
        this.collegeId = collegeId == null ? null : collegeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.MAJOR_ID
     *
     * @return the value of sims_class.MAJOR_ID
     *
     * @mbggenerated
     */
    public String getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.MAJOR_ID
     *
     * @param majorId the value for sims_class.MAJOR_ID
     *
     * @mbggenerated
     */
    public void setMajorId(String majorId) {
        this.majorId = majorId == null ? null : majorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.NAME
     *
     * @return the value of sims_class.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.NAME
     *
     * @param name the value for sims_class.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.STUDENT_NUMBER
     *
     * @return the value of sims_class.STUDENT_NUMBER
     *
     * @mbggenerated
     */
    public Integer getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.STUDENT_NUMBER
     *
     * @param studentNumber the value for sims_class.STUDENT_NUMBER
     *
     * @mbggenerated
     */
    public void setStudentNumber(Integer studentNumber) {
        this.studentNumber = studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.ADVISER
     *
     * @return the value of sims_class.ADVISER
     *
     * @mbggenerated
     */
    public String getAdviser() {
        return adviser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.ADVISER
     *
     * @param adviser the value for sims_class.ADVISER
     *
     * @mbggenerated
     */
    public void setAdviser(String adviser) {
        this.adviser = adviser == null ? null : adviser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.ESTAB_DATE
     *
     * @return the value of sims_class.ESTAB_DATE
     *
     * @mbggenerated
     */
    public Date getEstabDate() {
        return estabDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.ESTAB_DATE
     *
     * @param estabDate the value for sims_class.ESTAB_DATE
     *
     * @mbggenerated
     */
    public void setEstabDate(Date estabDate) {
        this.estabDate = estabDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.YEAR_NUMBER
     *
     * @return the value of sims_class.YEAR_NUMBER
     *
     * @mbggenerated
     */
    public Integer getYearNumber() {
        return yearNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.YEAR_NUMBER
     *
     * @param yearNumber the value for sims_class.YEAR_NUMBER
     *
     * @mbggenerated
     */
    public void setYearNumber(Integer yearNumber) {
        this.yearNumber = yearNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.CRATED_BY
     *
     * @return the value of sims_class.CRATED_BY
     *
     * @mbggenerated
     */
    public String getCratedBy() {
        return cratedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.CRATED_BY
     *
     * @param cratedBy the value for sims_class.CRATED_BY
     *
     * @mbggenerated
     */
    public void setCratedBy(String cratedBy) {
        this.cratedBy = cratedBy == null ? null : cratedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.CRATED_TIME
     *
     * @return the value of sims_class.CRATED_TIME
     *
     * @mbggenerated
     */
    public Date getCratedTime() {
        return cratedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.CRATED_TIME
     *
     * @param cratedTime the value for sims_class.CRATED_TIME
     *
     * @mbggenerated
     */
    public void setCratedTime(Date cratedTime) {
        this.cratedTime = cratedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.UPDATED_BY
     *
     * @return the value of sims_class.UPDATED_BY
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.UPDATED_BY
     *
     * @param updatedBy the value for sims_class.UPDATED_BY
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sims_class.UPDATED_TIME
     *
     * @return the value of sims_class.UPDATED_TIME
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sims_class.UPDATED_TIME
     *
     * @param updatedTime the value for sims_class.UPDATED_TIME
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}